remote_theme: pmarsceill/just-the-docs
title: "VinaNNeuro"
description: "Bookmark this to keep an eye on my project updates!"

# Navigation with dropdowns
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Data"
    children:
      - title: "TidyTuesday 2023"
        url: /2023-talks/
      - title: "TidyTuesday 2024"
        url: /2024-talks/
