# Site settings
title: "Your Website Title"
description: "A short description of your site."
baseurl: "" # e.g., /subpath
url: "https://yourusername.github.io" # Your site URL

# Norlin theme settings
theme: norlin

# Social media links (optional)
social:
  - name: GitHub
    icon: fab fa-github
    url: "https://github.com/yourusername"
  - name: LinkedIn
    icon: fab fa-linkedin
    url: "https://linkedin.com/in/yourusername"
  - name: Twitter
    icon: fab fa-twitter
    url: "https://twitter.com/yourusername"

# Appearance settings
logo: "/assets/images/logo.png" # Add a logo if you like
favicon: "/assets/images/favicon.ico"
accent_color: "#2e77ff" # Customize the primary accent color

# Navigation links
nav_links:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Blog"
    url: "/blog/"
  - name: "Projects"
    url: "/projects/"

# Markdown and options
markdown: kramdown
highlighter: rouge

# Plugins (if needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Pagination settings (optional)
paginate: 5 # Number of posts per page
paginate_path: "/page:num"

# Include and exclude files
exclude:
  - "README.md"
  - ".DS_Store"
