remote_theme: pmarsceill/just-the-docs
title: "VinaNNeuro"
description: "Bookmark this to keep an eye on my project updates!"

navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Data"
    has_children: true
    children:
      - title: "TidyTuesday"
        url: /tidytuesday/
