title: "VinaNNeuro"
description: "Bookmark this to keep an eye on my project updates!"
theme:  jekyll-theme-minimal

navigation:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about/"
  - name: "CV"
    link: "/cv/"
  - name: "Data"
    dropdown:
    - name: "TidyTuesday"
      link: /2023-talks/
