theme: minima
title: "VinaNeuro"
description: "Bookmark this to keep an eye on my project updates!"
author: "Vina"
email: "https://github.com/vina1998"
nav_links:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "CV"
    url: "/cv/"
  - name: "Data"
    url: "/data/"
