remote_theme: pmarsceill/just-the-docs
title: "VinaNeuro"
description: "Bookmark this to keep an eye on my project updates!"

# Navigation with dropdowns
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Data"
    children:
      - title: "TidyTuesday"
        url: /TT/
